name: GCS deployment
on:
    push:
        branches:
            main
        
jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v2
        with:
            service_account_email: ${{ secrets.sa_email }}
            service_account_key: ${{ secrets.sa_cred }}
            project_id: vocal-etching-439120-s6
      - name: Deploy via GCS
        run: |
          echo ${{ secrets.sa_email }}
          #gsutil rm gs://githubaction-bkt/*
          gsutil cp -r * gs://githubaction-bkt/
    
